# Generated by Django 4.1.4 on 2023-01-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_alter_library_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=200, null=True)),
                ("password", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
