# Generated by Django 4.1.4 on 2023-01-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
